@echo off
echo Starting PPreporter Client...
cd c:\dev\PPrePorter\Frontend\ppreporter-client
echo Installing dependencies if necessary...
call npm install
echo Starting development server...
call npm start
