using PPrePorter.Core.Models.Entities;
using CoreDailyAction = PPrePorter.Core.Models.Entities.DailyAction;
using DbDailyAction = PPrePorter.DailyActionsDB.Models.DailyActions.DailyAction;

namespace PPrePorter.Infrastructure.Adapters
{
    /// <summary>
    /// Adapter for converting between Core.Models.Entities.DailyAction and DailyActionsDB.Models.DailyActions.DailyAction
    /// </summary>
    public static class DailyActionAdapter
    {
        /// <summary>
        /// Converts a DailyActionsDB.Models.DailyActions.DailyAction to Core.Models.Entities.DailyAction
        /// </summary>
        public static CoreDailyAction ToCore(this DbDailyAction dbDailyAction)
        {
            return new CoreDailyAction
            {
                Id = dbDailyAction.Id,
                Date = dbDailyAction.Date,
                WhiteLabelID = dbDailyAction.WhiteLabelID,
                PlayerID = dbDailyAction.PlayerID,
                Registration = dbDailyAction.Registration.HasValue ? (int?)dbDailyAction.Registration.Value : null,
                FTD = dbDailyAction.FTD.HasValue ? (int?)dbDailyAction.FTD.Value : null,
                FTDA = dbDailyAction.FTDA.HasValue ? (int?)dbDailyAction.FTDA.Value : null,
                Deposits = dbDailyAction.Deposits,
                DepositsCreditCard = dbDailyAction.DepositsCreditCard,
                DepositsNeteller = dbDailyAction.DepositsNeteller,
                DepositsMoneyBookers = dbDailyAction.DepositsMoneyBookers,
                DepositsOther = dbDailyAction.DepositsOther,
                DepositsFee = dbDailyAction.DepositsFee,
                DepositsSport = dbDailyAction.DepositsSport,
                DepositsLive = dbDailyAction.DepositsLive,
                DepositsBingo = dbDailyAction.DepositsBingo,
                CashoutRequests = dbDailyAction.CashoutRequests,
                PaidCashouts = dbDailyAction.PaidCashouts,
                Chargebacks = dbDailyAction.Chargebacks,
                Voids = dbDailyAction.Voids,
                ReverseChargebacks = dbDailyAction.ReverseChargebacks,
                Bonuses = dbDailyAction.Bonuses,
                CollectedBonuses = dbDailyAction.CollectedBonuses,
                ExpiredBonuses = dbDailyAction.ExpiredBonuses,
                ClubPointsConversion = dbDailyAction.ClubPointsConversion,
                BankRoll = dbDailyAction.BankRoll,
                SideGamesBets = dbDailyAction.SideGamesBets,
                SideGamesRefunds = dbDailyAction.SideGamesRefunds,
                SideGamesWins = dbDailyAction.SideGamesWins,
                BetsCasino = dbDailyAction.BetsCasino,
                BetsCasinoReal = dbDailyAction.BetsCasinoReal,
                BetsCasinoBonus = dbDailyAction.BetsCasinoBonus,
                RefundsCasino = dbDailyAction.RefundsCasino,
                RefundsCasinoReal = dbDailyAction.RefundsCasinoReal,
                RefundsCasinoBonus = dbDailyAction.RefundsCasinoBonus,
                WinsCasino = dbDailyAction.WinsCasino,
                WinsCasinoReal = dbDailyAction.WinsCasinoReal,
                WinsCasinoBonus = dbDailyAction.WinsCasinoBonus,
                BetsSport = dbDailyAction.BetsSport,
                BetsSportReal = dbDailyAction.BetsSportReal,
                BetsSportBonus = dbDailyAction.BetsSportBonus,
                RefundsSport = dbDailyAction.RefundsSport,
                RefundsSportReal = dbDailyAction.RefundsSportReal,
                RefundsSportBonus = dbDailyAction.RefundsSportBonus,
                WinsSport = dbDailyAction.WinsSport,
                WinsSportReal = dbDailyAction.WinsSportReal,
                WinsSportBonus = dbDailyAction.WinsSportBonus,
                BetsLive = dbDailyAction.BetsLive,
                BetsLiveReal = dbDailyAction.BetsLiveReal,
                BetsLiveBonus = dbDailyAction.BetsLiveBonus,
                RefundsLive = dbDailyAction.RefundsLive,
                RefundsLiveReal = dbDailyAction.RefundsLiveReal,
                RefundsLiveBonus = dbDailyAction.RefundsLiveBonus,
                WinsLive = dbDailyAction.WinsLive,
                WinsLiveReal = dbDailyAction.WinsLiveReal,
                WinsLiveBonus = dbDailyAction.WinsLiveBonus,
                BetsBingo = dbDailyAction.BetsBingo,
                BetsBingoReal = dbDailyAction.BetsBingoReal,
                BetsBingoBonus = dbDailyAction.BetsBingoBonus,
                RefundsBingo = dbDailyAction.RefundsBingo,
                RefundsBingoReal = dbDailyAction.RefundsBingoReal,
                RefundsBingoBonus = dbDailyAction.RefundsBingoBonus,
                WinsBingo = dbDailyAction.WinsBingo,
                WinsBingoReal = dbDailyAction.WinsBingoReal,
                WinsBingoBonus = dbDailyAction.WinsBingoBonus,
                BonusesSport = dbDailyAction.BonusesSport,
                BonusesLive = dbDailyAction.BonusesLive,
                BonusesBingo = dbDailyAction.BonusesBingo,
                BonusConverted = dbDailyAction.BonusConverted,
                BetsReal = dbDailyAction.BetsReal,
                BetsBonus = dbDailyAction.BetsBonus,
                RefundsReal = dbDailyAction.RefundsReal,
                RefundsBonus = dbDailyAction.RefundsBonus,
                WinsReal = dbDailyAction.WinsReal,
                WinsBonus = dbDailyAction.WinsBonus,
                EUR2GBP = dbDailyAction.EUR2GBP
            };
        }

        /// <summary>
        /// Converts a Core.Models.Entities.DailyAction to DailyActionsDB.Models.DailyActions.DailyAction
        /// </summary>
        public static DbDailyAction ToDb(this CoreDailyAction coreDailyAction)
        {
            return new DbDailyAction
            {
                Id = coreDailyAction.Id,
                Date = coreDailyAction.Date,
                WhiteLabelID = coreDailyAction.WhiteLabelID,
                PlayerID = coreDailyAction.PlayerID,
                Registration = coreDailyAction.Registration.HasValue ? (byte?)Math.Min(255, coreDailyAction.Registration.Value) : null,
                FTD = coreDailyAction.FTD.HasValue ? (byte?)Math.Min(255, coreDailyAction.FTD.Value) : null,
                FTDA = coreDailyAction.FTDA.HasValue ? (byte?)Math.Min(255, coreDailyAction.FTDA.Value) : null,
                Deposits = coreDailyAction.Deposits,
                DepositsCreditCard = coreDailyAction.DepositsCreditCard,
                DepositsNeteller = coreDailyAction.DepositsNeteller,
                DepositsMoneyBookers = coreDailyAction.DepositsMoneyBookers,
                DepositsOther = coreDailyAction.DepositsOther,
                DepositsFee = coreDailyAction.DepositsFee,
                DepositsSport = coreDailyAction.DepositsSport,
                DepositsLive = coreDailyAction.DepositsLive,
                DepositsBingo = coreDailyAction.DepositsBingo,
                CashoutRequests = coreDailyAction.CashoutRequests,
                PaidCashouts = coreDailyAction.PaidCashouts,
                Chargebacks = coreDailyAction.Chargebacks,
                Voids = coreDailyAction.Voids,
                ReverseChargebacks = coreDailyAction.ReverseChargebacks,
                Bonuses = coreDailyAction.Bonuses,
                CollectedBonuses = coreDailyAction.CollectedBonuses,
                ExpiredBonuses = coreDailyAction.ExpiredBonuses,
                ClubPointsConversion = coreDailyAction.ClubPointsConversion,
                BankRoll = coreDailyAction.BankRoll,
                SideGamesBets = coreDailyAction.SideGamesBets,
                SideGamesRefunds = coreDailyAction.SideGamesRefunds,
                SideGamesWins = coreDailyAction.SideGamesWins,
                BetsCasino = coreDailyAction.BetsCasino,
                BetsCasinoReal = coreDailyAction.BetsCasinoReal,
                BetsCasinoBonus = coreDailyAction.BetsCasinoBonus,
                RefundsCasino = coreDailyAction.RefundsCasino,
                RefundsCasinoReal = coreDailyAction.RefundsCasinoReal,
                RefundsCasinoBonus = coreDailyAction.RefundsCasinoBonus,
                WinsCasino = coreDailyAction.WinsCasino,
                WinsCasinoReal = coreDailyAction.WinsCasinoReal,
                WinsCasinoBonus = coreDailyAction.WinsCasinoBonus,
                BetsSport = coreDailyAction.BetsSport,
                BetsSportReal = coreDailyAction.BetsSportReal,
                BetsSportBonus = coreDailyAction.BetsSportBonus,
                RefundsSport = coreDailyAction.RefundsSport,
                RefundsSportReal = coreDailyAction.RefundsSportReal,
                RefundsSportBonus = coreDailyAction.RefundsSportBonus,
                WinsSport = coreDailyAction.WinsSport,
                WinsSportReal = coreDailyAction.WinsSportReal,
                WinsSportBonus = coreDailyAction.WinsSportBonus,
                BetsLive = coreDailyAction.BetsLive,
                BetsLiveReal = coreDailyAction.BetsLiveReal,
                BetsLiveBonus = coreDailyAction.BetsLiveBonus,
                RefundsLive = coreDailyAction.RefundsLive,
                RefundsLiveReal = coreDailyAction.RefundsLiveReal,
                RefundsLiveBonus = coreDailyAction.RefundsLiveBonus,
                WinsLive = coreDailyAction.WinsLive,
                WinsLiveReal = coreDailyAction.WinsLiveReal,
                WinsLiveBonus = coreDailyAction.WinsLiveBonus,
                BetsBingo = coreDailyAction.BetsBingo,
                BetsBingoReal = coreDailyAction.BetsBingoReal,
                BetsBingoBonus = coreDailyAction.BetsBingoBonus,
                RefundsBingo = coreDailyAction.RefundsBingo,
                RefundsBingoReal = coreDailyAction.RefundsBingoReal,
                RefundsBingoBonus = coreDailyAction.RefundsBingoBonus,
                WinsBingo = coreDailyAction.WinsBingo,
                WinsBingoReal = coreDailyAction.WinsBingoReal,
                WinsBingoBonus = coreDailyAction.WinsBingoBonus,
                BonusesSport = coreDailyAction.BonusesSport,
                BonusesLive = coreDailyAction.BonusesLive,
                BonusesBingo = coreDailyAction.BonusesBingo,
                BonusConverted = coreDailyAction.BonusConverted,
                BetsReal = coreDailyAction.BetsReal,
                BetsBonus = coreDailyAction.BetsBonus,
                RefundsReal = coreDailyAction.RefundsReal,
                RefundsBonus = coreDailyAction.RefundsBonus,
                WinsReal = coreDailyAction.WinsReal,
                WinsBonus = coreDailyAction.WinsBonus,
                EUR2GBP = coreDailyAction.EUR2GBP
            };
        }
    }
}
