namespace PPrePorter.Core.Models.Entities.Dashboard
{
    /// <summary>
    /// Represents a top country in the dashboard
    /// </summary>
    public class TopCountryItem
    {
        /// <summary>
        /// Country code
        /// </summary>
        public string CountryCode { get; set; }

        /// <summary>
        /// Country name
        /// </summary>
        public string CountryName { get; set; }

        /// <summary>
        /// Number of players from this country
        /// </summary>
        public int PlayerCount { get; set; }

        /// <summary>
        /// Total revenue generated by players from this country
        /// </summary>
        public decimal Revenue { get; set; }

        /// <summary>
        /// Number of new registrations from this country
        /// </summary>
        public int RegistrationCount { get; set; }

        /// <summary>
        /// Total deposits made by players from this country
        /// </summary>
        public decimal TotalDeposits { get; set; }

        /// <summary>
        /// Average revenue per player from this country
        /// </summary>
        public decimal AverageRevenuePerPlayer { get; set; }

        /// <summary>
        /// Percentage change in player count compared to previous period
        /// </summary>
        public decimal PlayerCountChangePercentage { get; set; }

        /// <summary>
        /// Percentage change in revenue compared to previous period
        /// </summary>
        public decimal RevenueChangePercentage { get; set; }
    }
}
