namespace PPrePorter.Core.Models.Entities.Dashboard
{
    /// <summary>
    /// Represents a top performing game in the dashboard
    /// </summary>
    public class TopGameItem
    {
        /// <summary>
        /// Game ID
        /// </summary>
        public int GameId { get; set; }

        /// <summary>
        /// Game name
        /// </summary>
        public string GameName { get; set; }

        /// <summary>
        /// Game provider
        /// </summary>
        public string Provider { get; set; }

        /// <summary>
        /// Game type
        /// </summary>
        public string GameType { get; set; }

        /// <summary>
        /// Total revenue generated by the game
        /// </summary>
        public decimal Revenue { get; set; }

        /// <summary>
        /// Total bets placed on the game
        /// </summary>
        public decimal TotalBets { get; set; }

        /// <summary>
        /// Total wins paid out for the game
        /// </summary>
        public decimal TotalWins { get; set; }

        /// <summary>
        /// Number of unique players who played the game
        /// </summary>
        public int PlayerCount { get; set; }

        /// <summary>
        /// Number of rounds played
        /// </summary>
        public int RoundCount { get; set; }

        /// <summary>
        /// Average bet amount per round
        /// </summary>
        public decimal AverageBetAmount { get; set; }

        /// <summary>
        /// Return to player percentage
        /// </summary>
        public decimal RTP { get; set; }

        /// <summary>
        /// Percentage change in revenue compared to previous period
        /// </summary>
        public decimal RevenueChangePercentage { get; set; }

        /// <summary>
        /// Percentage change in player count compared to previous period
        /// </summary>
        public decimal PlayerCountChangePercentage { get; set; }
    }
}
