import { DashboardStats } from '../../../types/dashboard';
import { TransactionData } from '../../../types/redux';

/**
 * Analytics tab definition
 */
export interface AnalyticsTab {
  /**
   * Unique identifier for the tab
   */
  id: string;
  
  /**
   * Display label for the tab
   */
  label: string;
  
  /**
   * ARIA controls attribute value
   */
  ariaControls: string;
}

/**
 * Filter options for analytics data
 */
export interface FilterOptions {
  /**
   * Start date for filtering data (ISO string)
   */
  startDate: string;
  
  /**
   * End date for filtering data (ISO string)
   */
  endDate: string;
  
  /**
   * Country filter
   */
  country: string | null;
  
  /**
   * Game category filter
   */
  gameCategory: string | null;
  
  /**
   * Player status filter
   */
  playerStatus: string | null;
}

/**
 * Revenue data point
 */
export interface RevenueDataPoint {
  /**
   * Date of the data point
   */
  date: string;
  
  /**
   * Revenue value
   */
  revenue: number;
  
  /**
   * Number of players
   */
  players: number;
}

/**
 * Top game data
 */
export interface TopGameData {
  /**
   * Game ID
   */
  id: string;
  
  /**
   * Game name
   */
  name: string;
  
  /**
   * Game category
   */
  category: string;
  
  /**
   * Revenue generated by the game
   */
  revenue: number;
  
  /**
   * Number of players who played the game
   */
  players: number;
}

/**
 * Player registration data point
 */
export interface PlayerRegistrationDataPoint {
  /**
   * Date of the registration
   */
  date: string;
  
  /**
   * Number of registrations
   */
  count: number;
  
  /**
   * Conversion rate
   */
  conversionRate: number;
}

/**
 * Analytics state for Redux
 */
export interface AnalyticsState {
  /**
   * Dashboard summary statistics
   */
  summaryStats: DashboardStats | null;
  
  /**
   * Recent transactions data
   */
  recentTransactions: TransactionData[];
  
  /**
   * Casino revenue data
   */
  casinoRevenue: RevenueDataPoint[];
  
  /**
   * Top games data
   */
  topGames: TopGameData[];
  
  /**
   * Player registrations data
   */
  playerRegistrations: PlayerRegistrationDataPoint[];
  
  /**
   * Active tab index
   */
  activeTab: number;
  
  /**
   * Last updated timestamp (ISO string)
   */
  lastUpdated: string;
  
  /**
   * Filter options
   */
  filters: FilterOptions;
  
  /**
   * Loading state
   */
  isLoading: boolean;
  
  /**
   * Error state
   */
  error: string | null;
}

/**
 * Props for the OverviewTab component
 */
export interface OverviewTabProps {
  /**
   * Dashboard summary statistics
   */
  summaryStats: DashboardStats | null;
  
  /**
   * Recent transactions data
   */
  recentTransactions: TransactionData[];
  
  /**
   * Loading state
   */
  isLoading: boolean;
  
  /**
   * Error state
   */
  error: string | null;
}

/**
 * Props for the PerformanceTab component
 */
export interface PerformanceTabProps {
  /**
   * Casino revenue data
   */
  casinoRevenue: RevenueDataPoint[];
  
  /**
   * Loading state
   */
  isLoading: boolean;
  
  /**
   * Error state
   */
  error: string | null;
}

/**
 * Props for the PlayerAnalysisTab component
 */
export interface PlayerAnalysisTabProps {
  /**
   * Player registrations data
   */
  playerRegistrations: PlayerRegistrationDataPoint[];
  
  /**
   * Loading state
   */
  isLoading: boolean;
  
  /**
   * Error state
   */
  error: string | null;
}

/**
 * Props for the GameAnalysisTab component
 */
export interface GameAnalysisTabProps {
  /**
   * Top games data
   */
  topGames: TopGameData[];
  
  /**
   * Loading state
   */
  isLoading: boolean;
  
  /**
   * Error state
   */
  error: string | null;
}
